services:
  - type: web
    name: josephine-portfolio
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,*.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DEFAULT_FROM_EMAIL
        value: "josephineavomadoh@gmail.com"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "josephineavomadoh@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        sync: false
